name: benchmark

on:
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install PyAVL
        run: python setup.py install
      - name: Run benchmarks
        working-directory: ./tests
        run: python benchmark.py